learning-blog/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => LaravelLocalization::setLocale()], function(){

    /* Auth */
    Route::group(['prefix' => '/auth'], function(){
        Route::get('/login', 'AuthController@loginForm')->name('login');
        Route::post('/login', 'AuthController@login')->name('login-attempt');
        Route::get('/register', 'AuthController@registerForm')->name('register');
        Route::post('/register', 'AuthController@register')->name('register-user');
        Route::get('/logout', 'AuthController@logout')->name('logout');
    });

    Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Administrator|Editor']], function(){
        Route::get('/', 'AdminController@index')->name('index');


        /* Posts CRUD */
        Route::group(['prefix' => '/post', 'as' => 'post.'], function(){
            Route::get('/', 'PostController@index')->name('index');
            Route::get('/create', 'PostController@create')->name('create');
            Route::post('', 'PostController@store')->name('store');
            Route::get('/edit/{id}', 'PostController@edit')->name('edit');
            Route::post('/update/{id}', 'PostController@update')->name('update');
            Route::get('/delete/{id}', 'PostController@delete')->name('delete');
        });

        /* Post Categories CRUD */
        Route::group(['prefix' => '/post-category', 'as' => 'post_category.'], function(){
            Route::get('/', 'PostCategoryController@index')->name('index');
            Route::get('/create', 'PostCategoryController@create')->name('create');
            Route::post('', 'PostCategoryController@store')->name('store');
            Route::get('/edit/{id}', 'PostCategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'PostCategoryController@update')->name('update');
            Route::get('/delete/{id}', 'PostCategoryController@delete')->name('delete');
        });

        /* User CRUD */
        Route::group(['prefix' => '/user', 'as' => 'user.'], function(){
            Route::get('/', 'UserController@index')->name('index');
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('', 'UserController@store')->name('store');
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::post('/update/{id}', 'UserController@update')->name('update');
            Route::get('/delete/{id}', 'UserController@delete')->name('delete');
        });


        Route::group(['middleware' => ['role:Administrator']], function(){
            Route::get('/contact', 'ContactController@index')->name('contact.index');
            Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact.edit');
            Route::post('/contact/update/{id}', 'ContactController@update')->name('contact.update');
        });

        // Route::get('/admin/post', 'PostController@create')->name('post.create');
    });
});

learning-blog/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'as' => 'web.', 'middleware' => []], function(){
    Route::get('/', "WebController@index")->name('home');
    Route::get('/post/{id}', "WebController@post")->name('post.show');

    Route::get('/category/{id}', "WebController@category")->name('category.show');

    Route::group(['middleware' => ['auth']], function(){
        Route::post('/post/{id}/comment', 'WebController@postComment')->name('post.comment');

        Route::post('/post/{id}/rate', 'WebController@postRate')->name('post.rate');
    });

});

learning-blog/resources/views/admin/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>AdminLTE 3 | Dashboard 3</title>

  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{{mix('/assets/admin/css/app.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="/assets/admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Башкаруу панели</span>
    </a>

    @include('admin.layouts.sidebar')
  </aside>

  @yield('content')

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.5
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<script src="{{mix('/assets/admin/js/app.js')}}"></script>

@yield('scripts')
</body>
</html>

learning-blog/resources/views/admin/layouts/sidebar.blade.php
<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{asset(auth()->user()->image)}}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a class="d-block">{{auth()->user()->getFullName()}} </a>
        <a class="d-block">{{auth()->user()->getRoleNames()->first()}} </a>
        <a href="{{route('logout')}} ">{{trans('t.logout')}} </a>
      </div>
    </div>

<!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
      <li class="nav-header">Посттор</li>
      <li class="nav-item">
        <ul class="nav">
          <li class="nav-item">
            <a href="{{route('admin.post.index')}}" class="nav-link">
              <i class="fa fa-newspaper nav-icon"></i>
              <p>Посттор</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('admin.post_category.index')}}" class="nav-link">
              <i class="far fa-circle nav-icon"></i>
              <p>Категориялар</p>
            </a>
          </li>
        </ul>
      </li>
      @hasanyrole('Administrator')
      <li class="nav-item">
        <a href="{{route('admin.contact.index')}}" class="nav-link">
          <i class="nav-icon fa fa-address-card"></i>
          <p>
            Байланышуу
          </p>
        </a>
      </li>
      @endhasanyrole
      @hasanyrole('Administrator')
      <li class="nav-item">
        <a href="{{route('admin.user.index')}}" class="nav-link">
          <i class="nav-icon fa fa-address-card"></i>
          <p>
            Колдонуучулар
          </p>
        </a>
      </li>
      @endhasanyrole
    </ul>
  </nav>
  <!-- /.sidebar-menu -->


</div>
<!-- /.sidebar -->