learning-blog/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => LaravelLocalization::setLocale()], function(){

    /* Auth */
    Route::group(['prefix' => '/auth'], function(){
        Route::get('/login', 'AuthController@loginForm')->name('login');
        Route::post('/login', 'AuthController@login')->name('login-attempt');
        Route::get('/register', 'AuthController@registerForm')->name('register');
        Route::post('/register', 'AuthController@register')->name('register-user');
        Route::get('/logout', 'AuthController@logout')->name('logout');
    });

    Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Administrator|Editor']], function(){
        Route::get('/', 'AdminController@index')->name('index');


        /* Posts CRUD */
        Route::group(['prefix' => '/post', 'as' => 'post.'], function(){
            Route::get('/', 'PostController@index')->name('index');
            Route::get('/create', 'PostController@create')->name('create');
            Route::post('', 'PostController@store')->name('store');
            Route::get('/edit/{id}', 'PostController@edit')->name('edit');
            Route::post('/update/{id}', 'PostController@update')->name('update');
            Route::get('/delete/{id}', 'PostController@delete')->name('delete');
        });

        /* Post Categories CRUD */
        Route::group(['prefix' => '/post-category', 'as' => 'post_category.'], function(){
            Route::get('/', 'PostCategoryController@index')->name('index');
            Route::get('/create', 'PostCategoryController@create')->name('create');
            Route::post('', 'PostCategoryController@store')->name('store');
            Route::get('/edit/{id}', 'PostCategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'PostCategoryController@update')->name('update');
            Route::get('/delete/{id}', 'PostCategoryController@delete')->name('delete');
        });

        /* User CRUD */
        Route::group(['prefix' => '/user', 'as' => 'user.'], function(){
            Route::get('/', 'UserController@index')->name('index');
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('', 'UserController@store')->name('store');
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::post('/update/{id}', 'UserController@update')->name('update');
            Route::get('/delete/{id}', 'UserController@delete')->name('delete');
        });


        Route::group(['middleware' => ['role:Administrator']], function(){
            Route::get('/contact', 'ContactController@index')->name('contact.index');
            Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact.edit');
            Route::post('/contact/update/{id}', 'ContactController@update')->name('contact.update');
        });

        // Route::get('/admin/post', 'PostController@create')->name('post.create');
    });
});

learning-blog/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'as' => 'web.', 'middleware' => []], function(){
    Route::get('/', "WebController@index")->name('home');
    Route::get('/post/{id}', "WebController@post")->name('post.show');

    Route::get('/category/{id}', "WebController@category")->name('category.show');

    Route::group(['middleware' => ['auth']], function(){
        Route::post('/post/{id}/comment', 'WebController@postComment')->name('post.comment');

        Route::post('/post/{id}/rate', 'WebController@postRate')->name('post.rate');
    });

});

learning-blog/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;
use Intervention\Image\ImageManagerStatic as Image;


class Post extends Model
{
    protected $fillable = [
        'title',
        'description',
        'content',
        'active',
        'is_editors_pick',
        'category_id',
        'views',
    ];

    public function scores()
    {
        return $this->hasMany(Score::class);
    }

    public function getTotalScoreAttribute()
    {
        $scores = $this->scores;
        if($scores->count() > 0){
            $sum = 0;
            foreach($scores as $score){
                $sum = $sum + $score->value;
            }
            $average = $sum / $scores->count();
            return number_format($average, 2);
        }else{
            return trans('t.not_rated');
        }
    }

    public function category()
    {
        return $this->belongsTo(PostCategory::class, 'category_id')->withDefault(['title' => trans('t.no_category')]);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id')->withDefault([
            'name' => trans('t.no_author')
        ]);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'post_id')->whereNull('parent_comment_id');
    }

    public function allComments()
    {
        return $this->hasMany(Comment::class, 'post_id');
    }

    public function storeImage($file)
    {
        if($this->image){
            File::delete($this->image);
        }

        $folder = "assets/uploads/posts/{$this->id}";
        if(!file_exists($folder))
        {
            mkdir($folder, 0777, true);
        }

        $image_name = "image.jpg";

        $image_path = "{$folder}/{$image_name}";

        Image::make($file)->fit(1280, 720)->encode('jpg')->save($image_path);

        $this->image = $image_path;
        $this->save();
    }

    public function getImageAttribute($value)
    {
        if($value) return $value;
        return '/assets/uploads/posts/default_image.png';
    }

    public static function boot() {
	    parent::boot();

	    static::creating(function($item) {
            $item->user_id = auth()->user()->id;
	    });

	    static::updating(function($item) {
            $item->user_id = auth()->user()->id;
	    });

	    static::deleting(function($item) {
            if($item->image){
                File::deleteDirectory("assets/uploads/posts/{$item->id}");
            }
	    });
	}
}

learning-blog/app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\PostCategory;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        $rows = Post::all();
        return view('admin.post.index', compact('rows'));
    }

    public function create()
    {
        $row = new Post;
        $categories = PostCategory::all()->pluck('title', 'id');
        return view('admin.post.create', compact('row', 'categories'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required',
        ]);
        $row = Post::create($request->except('image'));

        if($request->hasFile('image')){
            $row->storeImage($request->file('image'));
        }

        return redirect()->route('admin.post.index');
    }

    public function edit($id)
    {
        $row = Post::findOrFail($id);
        $categories = PostCategory::all()->pluck('title', 'id');
        return view('admin.post.edit', compact('row', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required',
        ]);
        $row = Post::findOrFail($id);
        if($request->hasFile('image')){
            $row->storeImage($request->file('image'));
        }
        $row->update($request->except('image'));
        return redirect()->route('admin.post.index');
    }

    public function delete($id){
        $post = Post::findOrFail($id);
        $post->delete();
        return redirect()->back();
    }
}

learning-blog/resources/views/web/post/comment.blade.php
<li class="comment">
    <div class="vcard bio">
        <img src="{{asset($comment->author->image)}}" alt="Image placeholder">
    </div>
    <div class="comment-body">
        <h3>{{$comment->author->name}} </h3>
        <div class="meta">{{$comment->created_at->diffForHumans()}} </div>
        <h3>{{$comment->title}} </h3>
        <p>{{$comment->message}} </p>
        <p><a href="#" class="reply reply-to-comment" data-comment_id='{{$comment->id}}'>Reply</a></p>

    </div>

    @if($comment->replies->count())
    <ul class="children">
        @foreach($comment->replies as $comment)
        @include('web.post.comment', $comment)
        @endforeach
    </ul>
    @endif

</li>

learning-blog/resources/views/web/post/show.blade.php
@extends('web.layouts.base')

@section('title', $row->title)

@section('content')

<div class="site-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 single-content">

                <p class="mb-5">
                    <img src="{{asset($row->image)}}" alt="Image" class="img-fluid w-100">
                </p>
                <h1 class="mb-4">
                    {{$row->title}}
                </h1>
                <div class="post-meta d-flex mb-5">
                    <div class="bio-pic mr-3">
                        <img src="{{asset($row->author->image)}}" alt="Image" class="img-fluidid">
                    </div>
                    <div class="vcard">
                        <span class="d-block">
                            <a href="#">{{$row->author->name}} </a> in <a href="#">{{$row->category->title}} </a>
                        </span>
                        <span class="date-read">
                            {{$row->created_at->diffForHumans()}}
                            <span class="mx-1">&bullet;</span>
                            3 min read
                            <span class="icon-star2"></span>
                            {{$row->total_score}}
                            <span class="mx-1">&bullet;</span>
                            <span class="icon-eye"></span>
                            {{$row->views}}
                        </span>
                    </div>
                </div>

                {!! $row->content !!}

                <div class="pt-5">
                    <p>Categories: <a href="#">Design</a>, <a href="#">Events</a> Tags: <a href="#">#html</a>, <a
                            href="#">#trends</a></p>
                </div>


                <div class="pt-5">
                    <h2>{{trans('t.rate_this_post')}}: </h2>

                    @auth
                    <form id="rate-form" method="POST">
                        <div class="form-group">
                            <label class="pr-3">
                                1
                                <input type="radio" name="value" value="1">
                            </label>
                            <label class="pr-3">
                                2
                                <input type="radio" name="value" value="2">
                            </label>
                            <label class="pr-3">
                                3
                                <input type="radio" name="value" value="3">
                            </label>
                            <label class="pr-3">
                                4
                                <input type="radio" name="value" value="4">
                            </label>
                            <label class="pr-3">
                                5
                                <input type="radio" name="value" value="5">
                            </label>
                        </div>
                        <button class="btn btn-primary" type="submit">{{trans('t.rate')}} </button>
                    </form>
                    @else
                    <div class="comment-form-wrap pt-5">
                        <h3>{{trans('t.login_to_rate')}} </h3>
                        <a href="{{route('login')}} " class="btn btn-success">{{trans('t.login')}} </a>
                    </div>
                    @endauth
                </div>

                <div class="pt-5">
                    <div class="section-title">
                        <h2 class="mb-5">{{$row->allComments->count()}} {{trans('t.comments')}} </h2>
                    </div>
                    <ul class="comment-list">

                        @foreach($row->comments as $comment)
                        @include('web.post.comment', $comment)
                        @endforeach

                    </ul>
                    <!-- END comment-list -->

                    @auth
                    <div class="comment-form-wrap pt-5">
                        <div class="section-title">
                            <h2 class="mb-5">Leave a comment</h2>
                        </div>
                        <form action="{{route('web.post.comment', $row->id)}}" method="POST" class="p-5 bg-light">
                            @csrf
                            @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <li>{{$error}} </li>
                                @endforeach
                            </div>
                            @endif
                            <div class="form-group">
                                <label for="name">{{trans('t.title')}} *</label>
                                <input type="text" class="form-control" id="name" name="title">
                            </div>

                            <div class="form-group">
                                <label for="message">{{trans('t.message')}} </label>
                                <textarea name="message" id="message" cols="30" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn btn-primary py-3">
                            </div>

                        </form>
                    </div>
                    @else
                    <div class="comment-form-wrap pt-5">
                        <h3>{{trans('t.login_to_post_comment')}} </h3>
                        <a href="{{route('login')}} " class="btn btn-success">{{trans('t.login')}} </a>
                    </div>
                    @endauth

                </div>
            </div>


            <div class="col-lg-3 ml-auto">
                <div class="section-title">
                    <h2>Popular Posts</h2>
                </div>

                <div class="trend-entry d-flex">
                    <div class="number align-self-start">01</div>
                    <div class="trend-contents">
                        <h2><a href="blog-single.html">News Needs to Meet Its Audiences Where They Are</a></h2>
                        <div class="post-meta">
                            <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                            <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span
                                    class="icon-star2"></span></span>
                        </div>
                    </div>
                </div>

                <div class="trend-entry d-flex">
                    <div class="number align-self-start">02</div>
                    <div class="trend-contents">
                        <h2><a href="blog-single.html">News Needs to Meet Its Audiences Where They Are</a></h2>
                        <div class="post-meta">
                            <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                            <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span
                                    class="icon-star2"></span></span>
                        </div>
                    </div>
                </div>

                <div class="trend-entry d-flex">
                    <div class="number align-self-start">03</div>
                    <div class="trend-contents">
                        <h2><a href="blog-single.html">News Needs to Meet Its Audiences Where They Are</a></h2>
                        <div class="post-meta">
                            <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                            <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span
                                    class="icon-star2"></span></span>
                        </div>
                    </div>
                </div>

                <div class="trend-entry d-flex pl-0">
                    <div class="number align-self-start">04</div>
                    <div class="trend-contents">
                        <h2><a href="blog-single.html">News Needs to Meet Its Audiences Where They Are</a></h2>
                        <div class="post-meta">
                            <span class="d-block"><a href="#">Dave Rogers</a> in <a href="#">News</a></span>
                            <span class="date-read">Jun 14 <span class="mx-1">&bullet;</span> 3 min read <span
                                    class="icon-star2"></span></span>
                        </div>
                    </div>
                </div>

                <p>
                    <a href="#" class="more">See All Popular <span class="icon-keyboard_arrow_right"></span></a>
                </p>
            </div>


        </div>

    </div>
</div>
@endsection

@section('scripts')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>

    $("#rate-form").on('submit', function(e){
        e.preventDefault();
        var score = $('#rate-form input[name=value]:checked').val();

        if(score){
            $.ajax({
                method: "POST",
                url: "{{route("web.post.rate", $row->id)}}",
                data: {
                    _token: "{{csrf_token()}}",
                    value: score
                },
                success: function(res){
                    swal("{{trans('t.success')}}", res.message, 'success');
                },
                error: function(error){
                    swal("{{trans('t.error')}}", JSON.parse(error.responseText).message, 'error');
                }
            });
        }else{
            alert("{{trans("t.value_not_provided")}}");
        }
    });

    function generateCommentForm(id){
        return `<div class="comment-form-wrap pt-1 reply-form">
                <div class="">
                    <h3 class="">Reply a comment</h3>
                    <button class="btn btn-sm btn-dark float-right remove-reply-form" >x</button>
                </div>
                <form action="{{route('web.post.comment', $row->id)}}" method="POST" class="p-3 bg-light">
                    @csrf
                    <input type="hidden" name="parent_comment_id" value='${id}'>
                    <div class="form-group">
                        <label for="name">{{trans('t.title')}} *</label>
                        <input type="text" class="form-control" id="name" name="title">
                    </div>

                    <div class="form-group">
                        <label for="message">{{trans('t.message')}} </label>
                        <textarea name="message" id="message" cols="30" rows="3" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Post Comment" class="btn btn-primary py-3">
                    </div>

                </form>
            </div>`;
    }

    $(document).on('click', '.reply-to-comment', function(e){
        e.preventDefault();
        var button = $(this)[0];
        var buttonContainer = $(button).closest('.comment-body')[0];

        if($(buttonContainer).children('.reply-form').length == 0){
            var commentId = $(button).data('comment_id');
            $(buttonContainer).append(generateCommentForm(commentId));
        }
    });

    $(document).on('click', '.remove-reply-form', function(e){
        var container = $(this).closest('.reply-form');
        if(container.length){
            container[0].remove();
        }
    });


</script>

@endsection