learning-blog/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => LaravelLocalization::setLocale()], function(){

    /* Auth */
    Route::group(['prefix' => '/auth'], function(){
        Route::get('/login', 'AuthController@loginForm')->name('login');
        Route::post('/login', 'AuthController@login')->name('login-attempt');
        Route::get('/register', 'AuthController@registerForm')->name('register');
        Route::post('/register', 'AuthController@register')->name('register-user');
        Route::get('/logout', 'AuthController@logout')->name('logout');
    });

    Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Administrator|Editor']], function(){
        Route::get('/', 'AdminController@index')->name('index');


        /* Posts CRUD */
        Route::group(['prefix' => '/post', 'as' => 'post.'], function(){
            Route::get('/', 'PostController@index')->name('index');
            Route::get('/create', 'PostController@create')->name('create');
            Route::post('', 'PostController@store')->name('store');
            Route::get('/edit/{id}', 'PostController@edit')->name('edit');
            Route::post('/update/{id}', 'PostController@update')->name('update');
            Route::get('/delete/{id}', 'PostController@delete')->name('delete');
        });

        /* Post Categories CRUD */
        Route::group(['prefix' => '/post-category', 'as' => 'post_category.'], function(){
            Route::get('/', 'PostCategoryController@index')->name('index');
            Route::get('/create', 'PostCategoryController@create')->name('create');
            Route::post('', 'PostCategoryController@store')->name('store');
            Route::get('/edit/{id}', 'PostCategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'PostCategoryController@update')->name('update');
            Route::get('/delete/{id}', 'PostCategoryController@delete')->name('delete');
        });

        /* User CRUD */
        Route::group(['prefix' => '/user', 'as' => 'user.'], function(){
            Route::get('/', 'UserController@index')->name('index');
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('', 'UserController@store')->name('store');
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::post('/update/{id}', 'UserController@update')->name('update');
            Route::get('/delete/{id}', 'UserController@delete')->name('delete');
        });


        Route::group(['middleware' => ['role:Administrator']], function(){
            Route::get('/contact', 'ContactController@index')->name('contact.index');
            Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact.edit');
            Route::post('/contact/update/{id}', 'ContactController@update')->name('contact.update');
        });

        // Route::get('/admin/post', 'PostController@create')->name('post.create');
    });
});

learning-blog/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'as' => 'web.', 'middleware' => []], function(){
    Route::get('/', "WebController@index")->name('home');
    Route::get('/post/{id}', "WebController@post")->name('post.show');

    Route::get('/category/{id}', "WebController@category")->name('category.show');

    Route::group(['middleware' => ['auth']], function(){
        Route::post('/post/{id}/comment', 'WebController@postComment')->name('post.comment');

        Route::post('/post/{id}/rate', 'WebController@postRate')->name('post.rate');
    });

});

learning-blog/resources/views/web/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>@yield('title', 'Пайдалуу блог') </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cabin:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{mix('/assets/css/dist.css')}}">
    <link rel="stylesheet" href="{{mix('/assets/css/app.css')}}">
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    <div class="site-wrap">

        @include('web.layouts.header')

        @yield('content')

        @include('web.layouts.footer')


    </div>
    <!-- .site-wrap -->

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#ff5e15" /></svg></div>

    <script src="{{mix('/assets/js/app.js')}}"></script>

    @yield('scripts')

</body>

</html>

learning-blog/resources/views/web/layouts/footer.blade.php
<div class="site-section subscribe bg-light">
    <div class="container">
      <form action="#" class="row align-items-center">
        <div class="col-md-5 mr-auto">
          <h2>Newsletter Subcribe</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis aspernatur ut at quae omnis pariatur obcaecati possimus nisi ea iste!</p>
        </div>
        <div class="col-md-6 ml-auto">
          <div class="d-flex">
            <input type="email" class="form-control" placeholder="Enter your email">
            <button type="submit" class="btn btn-secondary" ><span class="icon-paper-plane"></span></button>
          </div>
        </div>
      </form>
    </div>
  </div>


  <div class="footer">
    <div class="container">


      <div class="row">
        <div class="col-12">
          <div class="copyright">
              <p>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  </p>
          </div>
        </div>
      </div>
    </div>
  </div>

learning-blog/resources/views/web/layouts/header.blade.php
<div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body"></div>
</div>



<div class="header-top">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg-6 d-flex">
                <a href="{{route('web.home')}}" class="site-logo">
                    Башкы бет
                </a>

                <a href="#" class="ml-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                        class="icon-menu h3"></span></a>

            </div>
            <div class="col-12 col-lg-6 ml-auto d-flex">
                <div class="ml-md-auto top-social d-none d-lg-inline-block">
                    @foreach ($nav_contacts as $item)
                        <a href="{{$item->value}}" class="d-inline-block p-3" target="_blank"><span class="{{$item->icon}}"></span></a>
                    @endforeach
                </div>
                <form action="#" class="search-form d-inline-block">

                    <div class="d-flex">
                        <input type="email" class="form-control" placeholder="Search...">
                        <button type="submit" class="btn btn-secondary"><span class="icon-search"></span></button>
                    </div>
                </form>
                <div class="ml-md-auto top-social d-none d-lg-inline-block">
                        @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                            @if(app()->getLocale() != $localeCode)
                            <a class="p-3" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                                <i class="flag-icon flag-icon-{{$localeCode}}"></i> {{ $properties['native'] }}
                            </a>
                            @endif
                        @endforeach
                </div>


            </div>
            <div class="col-6 d-block d-lg-none text-right">

            </div>
        </div>
    </div>




    <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">

        <div class="container">
            <div class="d-flex align-items-center">

                <div class="mr-auto">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mr-auto d-none pl-0 d-lg-block">

                            @foreach ($nav_categories as $row)
                            <li class="">
                                <a href="{{route('web.category.show', $row->id)}}" class="nav-link text-left">{{$row->title}} </a>
                            </li>
                            @endforeach
                        </ul>
                    </nav>

                </div>

            </div>
        </div>

    </div>