learning-blog/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => LaravelLocalization::setLocale()], function(){

    /* Auth */
    Route::group(['prefix' => '/auth'], function(){
        Route::get('/login', 'AuthController@loginForm')->name('login');
        Route::post('/login', 'AuthController@login')->name('login-attempt');
        Route::get('/register', 'AuthController@registerForm')->name('register');
        Route::post('/register', 'AuthController@register')->name('register-user');
        Route::get('/logout', 'AuthController@logout')->name('logout');
    });

    Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Administrator|Editor']], function(){
        Route::get('/', 'AdminController@index')->name('index');


        /* Posts CRUD */
        Route::group(['prefix' => '/post', 'as' => 'post.'], function(){
            Route::get('/', 'PostController@index')->name('index');
            Route::get('/create', 'PostController@create')->name('create');
            Route::post('', 'PostController@store')->name('store');
            Route::get('/edit/{id}', 'PostController@edit')->name('edit');
            Route::post('/update/{id}', 'PostController@update')->name('update');
            Route::get('/delete/{id}', 'PostController@delete')->name('delete');
        });

        /* Post Categories CRUD */
        Route::group(['prefix' => '/post-category', 'as' => 'post_category.'], function(){
            Route::get('/', 'PostCategoryController@index')->name('index');
            Route::get('/create', 'PostCategoryController@create')->name('create');
            Route::post('', 'PostCategoryController@store')->name('store');
            Route::get('/edit/{id}', 'PostCategoryController@edit')->name('edit');
            Route::post('/update/{id}', 'PostCategoryController@update')->name('update');
            Route::get('/delete/{id}', 'PostCategoryController@delete')->name('delete');
        });

        /* User CRUD */
        Route::group(['prefix' => '/user', 'as' => 'user.'], function(){
            Route::get('/', 'UserController@index')->name('index');
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('', 'UserController@store')->name('store');
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::post('/update/{id}', 'UserController@update')->name('update');
            Route::get('/delete/{id}', 'UserController@delete')->name('delete');
        });


        Route::group(['middleware' => ['role:Administrator']], function(){
            Route::get('/contact', 'ContactController@index')->name('contact.index');
            Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact.edit');
            Route::post('/contact/update/{id}', 'ContactController@update')->name('contact.update');
        });

        // Route::get('/admin/post', 'PostController@create')->name('post.create');
    });
});

learning-blog/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'as' => 'web.', 'middleware' => []], function(){
    Route::get('/', "WebController@index")->name('home');
    Route::get('/post/{id}', "WebController@post")->name('post.show');

    Route::get('/category/{id}', "WebController@category")->name('category.show');

    Route::group(['middleware' => ['auth']], function(){
        Route::post('/post/{id}/comment', 'WebController@postComment')->name('post.comment');

        Route::post('/post/{id}/rate', 'WebController@postRate')->name('post.rate');
    });

});

learning-blog/app/Models/PostCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PostCategory extends Model
{
    protected $fillable = [
        'title',
        'description',
        'is_important',
        'active',
    ];

    public $timestamps = false;

    public function posts()
    {
        return $this->hasMany(Post::class, 'category_id');
    }

}

learning-blog/app/Http/Controllers/Admin/PostCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PostCategory;
use Illuminate\Http\Request;

class PostCategoryController extends Controller
{
    public function index()
    {
        $rows = PostCategory::all();
        return view('admin.post_category.index', compact('rows'));
    }

    public function create()
    {
        $row = new PostCategory;
        return view('admin.post_category.create', compact('row'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        PostCategory::create($request->except('image'));

        return redirect()->route('admin.post_category.index');
    }

    public function edit($id)
    {
        $row = PostCategory::findOrFail($id);
        return view('admin.post_category.edit', compact('row'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
        ]);
        $post = PostCategory::findOrFail($id);
        $post->update($request->except('image'));

        return redirect()->route('admin.post_category.index');
    }

    public function delete($id){
        $post = PostCategory::findOrFail($id);
        $post->delete();
        return redirect()->back();
    }
}

learning-blog/resources/views/admin/post_category/create.blade.php
@extends('admin.layouts.base')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{trans('t.post_categories')}}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{trans('t.main')}}</a></li>
                        <li class="breadcrumb-item active">{{trans('t.post_categories')}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{trans('t.new_post_category')}}</h3>
                            <div class="float-right">
                                <a href="{{route('admin.post.index')}}"
                                    class="btn btn-primary">{{trans('t.post_categories')}}</a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        {!! Form::model($row, ['role' => 'form', 'method' => 'POST', 'route' => ['admin.post_category.store']]) !!}
                        @include('admin.post_category.form')
                        {!! Form::close() !!}
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

learning-blog/resources/views/admin/post_category/edit.blade.php
@extends('admin.layouts.base')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{trans('t.posts')}}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{trans('t.main')}}</a></li>
                        <li class="breadcrumb-item active">{{trans('t.posts')}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{trans('t.new_post')}}</h3>
                            <div class="float-right">
                                <a href="{{route('admin.post.index')}}"
                                    class="btn btn-primary">{{trans('t.all_posts')}}</a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        {!! Form::model($row, ['role' => 'form', 'method' => 'POST', 'route' =>
                        ['admin.post_category.update',
                        $row->id]]) !!}
                        @include('admin.post_category.form')
                        {!! Form::close() !!}
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

learning-blog/resources/views/admin/post_category/form.blade.php
<div class="card-body">
    <div class="form-group">
        <label>{{trans('t.title')}}</label>
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        <label>Түшүндүрмө</label>
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-check">
        {!! Form::hidden('is_important', 0) !!}
        {!! Form::checkbox('is_important', 1, null, ['class' => 'form-check-input', 'id' => 'is_important']) !!}
        <label class="form-check-label" for="is_important">Башкы бетке чыгаруу</label>
    </div>
    <div class="form-check">
        {!! Form::hidden('active', 0) !!}
        {!! Form::checkbox('active', 1, null, ['class' => 'form-check-input', 'id' => 'exampleCheck1']) !!}
        <label class="form-check-label" for="exampleCheck1">Активдүү</label>
    </div>
</div>
<!-- /.card-body -->

<div class="card-footer">
    <button type="submit" class="btn btn-success">Сактоо</button>
</div>

learning-blog/resources/views/admin/post_category/index.blade.php
@extends('admin.layouts.base')

@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{trans('t.post_categories')}}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">{{trans('t.main')}}</a></li>
              <li class="breadcrumb-item active">{{trans('t.post_categories')}}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
                <div class="card-header">
                  <h3 class="card-title">{{trans('t.all_post_categories')}}</h3>
                  <div class="float-right">
                      <a href="{{route('admin.post_category.create')}}" class="btn btn-primary">{{trans('t.post_category_create')}}</a>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>ID</th>
                      <th>{{trans('t.title')}}</th>
                      <th>{{trans('t.posts_amount')}}</th>
                      <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($rows as $item)
                        <tr>
                            <td>{{$item->id}}</td>
                            <td>{{$item->title}}</td>
                            <td>{{$item->posts->count()}}</td>
                            <td>
                                <a href="{{route('admin.post_category.edit', $item->id)}}" class="btn btn-warning">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a onclick="return confirm('{{trans('t.confirm_delete')}}')" href="{{route('admin.post_category.delete', $item->id)}}" class="btn btn-danger">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                    <tr>
                      <th>ID</th>
                      <th>{{trans('t.title')}}</th>
                      <th>{{trans('t.posts_amount')}}</th>
                      <th></th>
                    </tr>
                    </tfoot>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
          </div>
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection